apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  labels:
    app: {{.Values.name}}
spec:
  selector:
    app: {{.Values.name}}
  type: {{.Values.serviceType}}
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.serviceTargetPort}}
      nodePort: {{.Values.NodePort}}
